
package at.fhooe.mc.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISimpleInterface", targetNamespace = "http://service.jaxws.mc.fhooe.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISimpleInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns at.fhooe.mc.jaxws.client.DummyData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://service.jaxws.mc.fhooe.at/", className = "at.fhooe.mc.jaxws.client.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://service.jaxws.mc.fhooe.at/", className = "at.fhooe.mc.jaxws.client.GetDataResponse")
    @Action(input = "http://service.jaxws.mc.fhooe.at/ISimpleInterface/getDataRequest", output = "http://service.jaxws.mc.fhooe.at/ISimpleInterface/getDataResponse")
    public DummyData getData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saySomething", targetNamespace = "http://service.jaxws.mc.fhooe.at/", className = "at.fhooe.mc.jaxws.client.SaySomething")
    @ResponseWrapper(localName = "saySomethingResponse", targetNamespace = "http://service.jaxws.mc.fhooe.at/", className = "at.fhooe.mc.jaxws.client.SaySomethingResponse")
    @Action(input = "http://service.jaxws.mc.fhooe.at/ISimpleInterface/saySomethingRequest", output = "http://service.jaxws.mc.fhooe.at/ISimpleInterface/saySomethingResponse")
    public String saySomething();

}
